"""ComfyUI-PrimitiveAnything nodes package."""

from .load_model import NODE_CLASS_MAPPINGS as LOAD_MAPPINGS
from .load_model import NODE_DISPLAY_NAME_MAPPINGS as LOAD_DISPLAY

from .primitives import NODE_CLASS_MAPPINGS as PRIMITIVES_MAPPINGS
from .primitives import NODE_DISPLAY_NAME_MAPPINGS as PRIMITIVES_DISPLAY

from .preprocess import NODE_CLASS_MAPPINGS as PREPROCESS_MAPPINGS
from .preprocess import NODE_DISPLAY_NAME_MAPPINGS as PREPROCESS_DISPLAY

from .process import NODE_CLASS_MAPPINGS as PROCESS_MAPPINGS
from .process import NODE_DISPLAY_NAME_MAPPINGS as PROCESS_DISPLAY


# Aggregate all node mappings
NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(LOAD_MAPPINGS)
NODE_CLASS_MAPPINGS.update(PRIMITIVES_MAPPINGS)  # New merged node
NODE_CLASS_MAPPINGS.update(PREPROCESS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(PROCESS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS.update(LOAD_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(PRIMITIVES_DISPLAY)  # New merged node
NODE_DISPLAY_NAME_MAPPINGS.update(PREPROCESS_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(PROCESS_DISPLAY)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
